### ISSUE TITLE
Please add license to package.json

### ISSUE THREAD

**Issue by jinder** [bramstein/url-template#12]
Please could you add the BSD license to package.json?  This will ensure that any automated tools that check the license on NPM will be able to determine it's BSD-based.  Thank you.

**Comment by bramstein** [comment]
Excellent idea. Done. Thanks for letting me know.

**Comment by jinder** [comment]
Great thanks!  If you could push this to NPM that would be great :)Great thanks!  If you could push this to NPM that would be great :)

**Comment by bramstein** [comment]
It should already be there :)
