### ISSUE TITLE
"that.encodeReserved is not a function" when parse() is called

### ISSUE THREAD

**Issue by dynnamitt** [bramstein/url-template#13]
TypeError: that.encodeReserved is not a function
   at /opt/PROJECT/node_modules/url-template/lib/url-template.js:171:25
   at String.replace (native)

summary of code in main file of express app

t = urlTempl.parse(href); // works fine , called in main file

// called inside a route;
url = t.expand( { email: req.params.email } ); // above error

I try to replicate this issue in my tests .. but I must be missing something obvious
because url-temple always manage to work there ...

**Comment by dynnamitt** [comment]
"that" looses some prototype props inside routes and precompiled templates cannot be used there?

Could it be that
line 37 , function  UrlTemplate.prototype.encodeValue also need to store "this" into "that" ??

**Comment by dynnamitt** [comment]
my bad, I used JS "legacy-semi-best-practice"

var parse = require("url-template").parse,
      templ = parse("url/{x}"),
      url = templ.expand({x:1});      // throws !!

Back to COFFESCRIFT :-p

**Comment by donaldpipowitch** [comment]
What is the problem with that? I use

```
import { parse } from 'url-template';
const parsedIUrl = parse('some-url');
parsedUrl.expand(someData);
```

It should work or not?
