### ISSUE TITLE
option to leave unknown params

### ISSUE THREAD

**Issue by figadore** [bramstein/url-template#14]
Would it be acceptable to add an option to the `expand` function which would allow parameters to be expanded only if they are known/set? For example

```
var template = urlTemplate.parse('/cars/{model}/engine/{engineId}');
console.log(urlTemplate.expand({model: "ford-taurus"}, false);
// "/cars/ford-taurus/engine/{engineId}"
```

see [my fork](https://github.com/shinymayhem/url-template/commit/6d4925154a5b3a8ce269f6b2f87cf59171456702) for the hack i'm currently using

My use case is for dynamic generation of hypermedia links for subresources where certain parameters are known, but other still need to be filled in

**Comment by danosaure** [comment]
I ran into this issue today. I would not put that new optional param as `false`, but it should be:

expand(data, [partial])

so unless `partial` is truthty, then apply RFC.

**Comment by jonkoops** [comment]
Is it part of the specification that these kind of fields can be omitted? It seems like an error to me if folks are missing some parameters.

**Comment by jonkoops** [comment]
Closing this issue to to lack of response, feel free to open up a new issue if this is still relevant.
