### ISSUE TITLE
Parse should parse

### ISSUE THREAD

**Issue by mfowlewebs** [bramstein/url-template#24]
At present `parse` returns an object with a an `expand` method in it. Parse does not do any ahead of time work, all of the work of [parsing the template](https://github.com/bramstein/url-template/blob/master/lib/url-template.js#L156) &c is part of the second expand method.

Ideally, parse would do some parsing work, such that the `expand` method could be shorter & do less work. If I am trying to make 1000 requests/second to a service, I don't want to have to keep re-parsing the template for each of these requests: I'd expect the `parse` method to break up & parse the template, such that the `expand` method could simply drop values into place & go.

**Comment by jonkoops** [comment]
@mfowlewebs Have not looked into this extensively, but does #20 cover this request?

**Comment by jonkoops** [comment]
Closing this due to lack of response, if this issue is still relevant feel free to open up a new one.
