### ISSUE TITLE
Incorrect Types for expand.

### ISSUE THREAD

**Issue by MarkTallentire** [bramstein/url-template#57]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `url-template@3.1.0` for the project I'm working on.

Type was incorrect for Template.expand as it did not allow objects that contain arrays. Resolved by changing the type as below.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/url-template/lib/url-template.d.ts b/node_modules/url-template/lib/url-template.d.ts
index feae94a..8a9b227 100644
--- a/node_modules/url-template/lib/url-template.d.ts
+++ b/node_modules/url-template/lib/url-template.d.ts
@@ -1,7 +1,7 @@
 export type PrimitiveValue = string | number | boolean | null;
 
 export interface Template {
-  expand(context: Record<string, PrimitiveValue | PrimitiveValue[] | Record<string, PrimitiveValue>>): string;
+  expand(context: Record<string, PrimitiveValue | PrimitiveValue[] | Record<string, PrimitiveValue | PrimitiveValue[]>>): string;
 }
 
 export function parseTemplate(template: string): Template;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by jamesfoster** [comment]
I had the same issue. I've tested the behaviour of expand with objects containing lists.

```js
var template = parseTemplate("/test/{?keys*}");
var url = template.expand({ keys: { value: "a", array: ["b", "c"]}})

url == "/test/?value=a&array=b%2Cc"
```

Unfortunately this isn't correct cos when read back you'd end up with `array = ["b,c"]`. It should probably output

`/test/?value=a&array=b,c`
or
`/test/?value=a&array=b&array=c`
