### ISSUE TITLE
3.0.0 migration guide suggests cjs syntax is usable but we get errors when we use require.  Please clarify if CJS is supported

### ISSUE THREAD

**Issue by mike-lang** [bramstein/url-template#59]
Hi,

The 3.0.0 migration guide suggests I can use the following syntax to use version 3.0.0:
```
const { parseTemplate } = require('url-template');
const emailUrlTemplate = parseTemplate('/{email}/{folder}/{id}');
```

But when I do so in my project I get the following error message:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /root/*********/browzine_cms/node_modules/url-template/lib/url-template.js
require() of ES modules is not supported.
require() of /root/*********/browzine_cms/node_modules/url-template/lib/url-template.js from /root/*********/browzine_cms/lib/models/user_model.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename url-template.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /root/*********/browzine_cms/node_modules/url-template/package.json.
```

Can you advise if CJS style imports are actually still intended to be supported?  Do I need to do something on my end or is this an issue in `url-template` that the syntax in the migration guide isn't working?

**Comment by jonkoops** [comment]
This is a mistake, ESM modules can only be imported from CommonJS using the `import()` API. I've updated the migration guide to reflect this.

My recommendation would be to convert your code to ESM as much as possible.
